[package]
name = "cmapi"
version = "0.1.0"
authors = ["alan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.116"
serde_derive = "1.0.116"
restson = "0.7.0"
anyhow = "1.0"